# Site settings
title: "CPP For CP"
author: "Priyanshu Tiwari"
description: "A cocktail of all the data structures and algorithms for competitive programming in C++"
keywords: "CPP, STL, Algorithm, DSA, Maths, Priyanshu, Tiwari, ahampriyanshu, website, c++, c, plus, resources"
biography: "Hello I'm Priyanshu Tiwari, an undergrad student and full-stack web developer based in India. Beside programming, I love cinema, history, comedy, politics and experimenting with equity market."
       
url: https://cpp.ahampriyanshu.com
baseurl: ""
google-analytics: GTM-598SW68

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
plugins:
  - jekyll-sitemap